name: awesome_location_picker
description: "The best Flutter package for picking Country, State, and City with cascading dropdowns.
  Powerful, customizable, and easy to integrate."
version: 0.0.5
license: MIT
homepage: https://github.com/rahmanprofile/awesome_location_picker
repository: https://github.com/rahmanprofile/awesome_location_picker
issue_tracker: https://github.com/rahmanprofile/awesome_location_picker/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# Your flutter assets or fonts here, if any
