name: awesome_location_picker
description: "A Flutter package to select Country, State, and City with cascading dropdowns."
version: 0.0.4
license: MIT
homepage: https://github.com/rahmanprofile/awesome_location_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# Your flutter assets or fonts here, if any
